# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP.NET Core service.

version: '3.4'

services:
  src:
    image: src
    container_name: esdb
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 5000:5000
    depends_on:
      eventstore.db:
        condition: service_healthy
        restart: true  

  eventstore.db:
    image: eventstore/eventstore:23.10.0-bookworm-slim
    container_name: node1
    environment:
      - EVENTSTORE_CLUSTER_SIZE=1
      - EVENTSTORE_RUN_PROJECTIONS=All
      - EVENTSTORE_START_STANDARD_PROJECTIONS=true
      - EVENTSTORE_EXT_TCP_PORT=1113
      - EVENTSTORE_HTTP_PORT=2113
      - EVENTSTORE_INSECURE=true
      - EVENTSTORE_ENABLE_EXTERNAL_TCP=true
      - EVENTSTORE_ENABLE_ATOM_PUB_OVER_HTTP=true
      - EVENTSTORE_EXT_IP=0.0.0.0
      - EVENTSTORE_ADVERTISE_HOST_TO_CLIENT_AS=node1
    ports:
      - "1113:1113"
      - "2113:2113"
    volumes:
      - type: volume
        source: eventstore-volume-data
        target: /var/lib/eventstore
      - type: volume
        source: eventstore-volume-logs
        target: /var/log/eventstore
    healthcheck:
        test:
          [
            "CMD-SHELL",
            "curl --fail --insecure http://node1:2113/health/live || exit 1",
          ]
        interval: 5s
        timeout: 5s
        retries: 24
volumes:
  eventstore-volume-data:
  eventstore-volume-logs: